import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import WaitlistForm from "./Waitlist"; // 1. Imported your waitlist component

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Araft Mk1", // Optimized for your project title
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-slate-950 text-slate-100">
        {/* Navbar will show on every page */}
        <Navbar />
        
        {/* Your dynamic pages render here */}
        <main className="flex-grow">{children}</main>
        
        {/* 2. Global footer containing the waitlist box */}
        <footer className="w-full border-t border-slate-900 bg-slate-950 py-10 mt-auto">
          <WaitlistForm />
        </footer>
      </body>
    </html>
  );
}

